### PR TITLE
allow user to add inner container class names to overlay

### PR DESCRIPTION
**Pull request by mattbreckon**
attach class names to overlay's inner container element.

```
{{#g.overlay innerContainerClassNames="pastafano" lat=lat lng=lng}}
{{/g.overlay}}
```

### CODE REVIEW

**Comment by sandydoo** [comment]
Thanks, @mattbreckon.

Would you mind sharing a snippet of how you're using this? I'd like to get an idea of the specific issue this tackles.

**Comment by mattbreckon** [comment]
trying to add/remove class names on `g-map/overlay` when a user hovers/clicks on a leg-detail component next to a map or if the waypoint meets certain conditions (like initial origin/final destination).

here's an example:

```
// parent-map-component.js

actions: {
  panTo(leg) {
    this.setActiveWaypoints(leg);

    const bounds = this.createBounds(leg);
    return this.get('googleMap.map').fitBounds(bounds);
  }
}, 

// child-leg-details-component.js

mouseEnter() {
  return this.get('panTo')(this.get('leg'));
},

mouseLeave() {
  return this.get('panAway')(this.get('leg'));
},

// child-overlay-component.hbs

{{#g.overlay
  innerContainerClassNames=computedOverlayClassNames
  lat=waypoint.lat
  lng=waypoint.lon
}}
  <div class="ui-map-overlay">...</div>
{{/g.overlay}}

// css

.waypoint-initial-origin,
.waypoint-final-destination {
  z-index: 50;
}

.waypoint-active {
  z-index: 100;

  .ui-map-overlay {
      transform: scale(1.75);
  }
}
```

does that make sense?

**Comment by sandydoo** [comment]
Thanks, @mattbreckon. I was away for a while, so I apologize for leaving you hanging.

The issue is that the "inner" element was really only intended for relative positioning, i.e. anchoring the overlay content. If we add classes to the mix, we introduce an order of precedence problem. For example, if your class contains a transform, it will be overridden by the style.

I think I've made a mistake with `innerContainerStyle`. It's unclear what it should be used for, allows for random styling, and has an awkward 'middle-bottom' default. Instead of encouraging adding styles and classes to that hidden inner element, I believe it's best to remove it altogether.

For simple styling, the better option would be to wrap your content directly, especially if you have transforms.

```hbs
{{#g.overlay
  lat=waypoint.lat
  lng=waypoint.lon}}
  <div class={{customClasses}}>
    {{!-- Content --}}
  </div>
{{/g.overlay}}
```

One problem I've noticed is the `z-index`. Due to the stacking context, there doesn't seem to be a  way to change the order of the overlays anymore. Are you sure your `z-index` styles work as intended? I think we'll need to add a `zIndex` option to solve this.

In the long run, I think the following makes more sense. We remove `innerContainerStyle`, show how to offset overlays in the docs, and add a `zIndex` option to deal with display order.

```css
.anchor-middle-bottom {
  transform: translateX(-50%) translateY(-100%);
}
```

```hbs
{{#each waypoints as |waypoint index|}}
  {{#g.overlay
    zIndex=(if waypoint.active "1000" index)
    lat=waypoint.lat
    lng=waypoint.lon}}
    <div class="anchor-middle-bottom">
      <div class={{customClasses}}>
        {{!-- Content --}}
      </div>
    </div>
  {{/g.overlay}}
{{/each}}
```

**Comment by sandydoo** [comment]
I'm closing this, since this can now be done in `v3.0.0-beta.0`. Thank you for bringing this up 🙇 

```css
.anchor-middle-bottom {
  transform: translateX(-50%) translateY(-100%);
}
```

```hbs
{{#each waypoints as |waypoint index|}}
  {{#g.overlay
    zIndex=(if waypoint.active "1000" index)
    lat=waypoint.lat
    lng=waypoint.lon}}
    <div class="anchor-middle-bottom">
      <div class={{customClasses}}>
        {{!-- Content --}}
      </div>
    </div>
  {{/g.overlay}}
{{/each}}
```

**Pull request closed without merging**
