### PR TITLE
Support loading addon components from in-repo addons

### PR DESCRIPTION
**Pull request by acorncom**
I've been working on a `g.data` addon for `ember-google-maps` for a client. I'm aiming to release it at some point, but at the moment we're fleshing out the API in-house. I started using an in-repo addon and noticed it wasn't currently supported.

Are you interested in having this addon support that configuration? Tests may fail here (I was getting api key issues locally), but I can ensure all tests are passing if you are interested in this change

### CODE REVIEW

**Comment by sandydoo** [comment]
Thanks for the PR! Yeah, let's merge this. Could I ask you to rename the in-repo addon? Anything with the word `in-repo` is good, so we don't forget what it's for.
The tests are failing because of eslint. It's unhappy that the `lib` path is linted as node. Perhaps we should just move the `addon-registry` file to another folder 😄

**Comment by acorncom** [comment]
@sandydoo tests all pass here at this point, let me know if you want me to tweak anything else 😃

**Comment by sandydoo** [comment]
Thanks, @acorncom. 👍

**Comment by acorncom** [comment]
Absolutely @sandydoo. Btw, I've been building a `drawing` addon for handling drawing new polygons onto maps. It's actually been ridiculously easy. I very much appreciate all the work on the addon system even if it's currently undocumented 😃

**Comment by sandydoo** [comment]
@acorncom, cool! I'm glad you're getting some use out of it 😄

**Comment by acorncom** [comment]
@sandydoo yeah, it's been fun. It turns out you can also fairly easily do things like setup routable maps:

```
{{#g-map as |g|}}
  {{g.outlet}}
{{/g-map}}
```

which then would let you control what data gets loaded onto the map in question ...

**Pull request merged**
